[package]
name = "pqc_bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
clap = { version = "4.5.50", features = ["derive"] }
pqc_dilithium = "0.2.0"
pqc_kyber = "0.7.1"
rand = "0.8.5"
sha3 = "0.10.8"
